#include <fstream>
#include <iostream>
#include <string>
#include <sstream>
#include <vector>
#include <set>
#include <tuple>
#include <map>
#include <string>
#include <algorithm>
#include <iterator>
#include <cmath>
#include <cstdlib>
#include <iomanip>
